from classicdemonlist.admin.classicleveladmin import CustomSortableAdminMixin, ClassicLevelAdmin
from classicdemonlist.admin.classicplayeradmin import ClassicPlayerAdmin
from classicdemonlist.admin.classiclevelrecordadmin import ClassicLevelRecordAdmin
from classicdemonlist.admin.classicregionadmin import ClassicRegionAdmin
from classicdemonlist.admin.classiclistchangeadmin import ClassicListChangeAdmin