# Generated by Django 4.2.4 on 2023-12-30 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelid', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(blank=True, choices=[('Hard Demon', 'Hard Demon'), ('Insane Demon', 'Insane Demon'), ('Extreme Demon', 'Extreme Demon')], max_length=255)),
                ('youtube_link', models.URLField(blank=True)),
                ('youtube_thumbnail', models.URLField(blank=True)),
                ('points', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name', 'points'],
            },
        ),
        migrations.CreateModel(
            name='PlatformerRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.FloatField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platformerdemonlist.platformerregion')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformerListChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change_type', models.CharField(choices=[('Place', 'Place'), ('Raise', 'Raise'), ('Lower', 'Lower'), ('Swap', 'Swap'), ('Remove', 'Remove'), ('List requirement', 'List requirement')], default=None, max_length=255)),
                ('placement', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('effect', models.CharField(blank=True, max_length=255)),
                ('custom_levelname', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_swapwith', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_abovelevelname', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_belowlevelname', models.CharField(blank=True, max_length=100, null=True)),
                ('above_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='above_level', to='platformerdemonlist.platformerlevel')),
                ('below_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='below_level', to='platformerdemonlist.platformerlevel')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformerdemonlist.platformerlevel')),
                ('swap_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_with', to='platformerdemonlist.platformerlevel')),
            ],
        ),
        migrations.AddField(
            model_name='platformerlevel',
            name='record_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platformerdemonlist.platformerplayer'),
        ),
        migrations.CreateModel(
            name='PlatformerLevelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('record_video_link', models.URLField(blank=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platformerdemonlist.platformerlevel')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformerdemonlist.platformerplayer')),
            ],
            options={
                'unique_together': {('level', 'player')},
            },
        ),
    ]
