# Generated by Django 4.2.6 on 2023-12-29 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformerdemonlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformerlevelrecord',
            name='record_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
