# Generated by Django 4.2.4 on 2024-01-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformerdemonlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformerlevel',
            options={'ordering': ['name', 'points'], 'verbose_name': 'Platformer Level', 'verbose_name_plural': 'Platformer Levels'},
        ),
        migrations.AlterModelOptions(
            name='platformerlevelrecord',
            options={'verbose_name': 'Platformer Level Record', 'verbose_name_plural': 'Platformer Level Records'},
        ),
        migrations.AlterModelOptions(
            name='platformerlistchange',
            options={'verbose_name': 'Platformer List Change', 'verbose_name_plural': 'Platformer List Changes'},
        ),
        migrations.AlterModelOptions(
            name='platformerplayer',
            options={'verbose_name': 'Platformer Player', 'verbose_name_plural': 'Platformer Players'},
        ),
        migrations.AlterModelOptions(
            name='platformerregion',
            options={'verbose_name': 'Platformer Region', 'verbose_name_plural': 'Platformer Regions'},
        ),
        migrations.AlterUniqueTogether(
            name='platformerlevelrecord',
            unique_together=set(),
        ),
    ]
