# Generated by Django 4.2.4 on 2024-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformerdemonlist', '0002_alter_platformerlevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformerlevel',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Medium Demon', 'Medium Demon'), ('Hard Demon', 'Hard Demon'), ('Insane Demon', 'Insane Demon'), ('Extreme Demon', 'Extreme Demon')], max_length=255),
        ),
    ]
