# Generated by Django 4.2.4 on 2024-01-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classicdemonlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classiclevel',
            options={'verbose_name': 'Classic Level', 'verbose_name_plural': 'Classic Levels'},
        ),
        migrations.AlterModelOptions(
            name='classiclevelrecord',
            options={'verbose_name': 'Classic Level Record', 'verbose_name_plural': 'Classic Level Records'},
        ),
        migrations.AlterModelOptions(
            name='classiclistchange',
            options={'verbose_name': 'Classic List Change', 'verbose_name_plural': 'Classic List Changes'},
        ),
        migrations.AlterModelOptions(
            name='classicplayer',
            options={'verbose_name': 'Classic Player', 'verbose_name_plural': 'Classic Players'},
        ),
        migrations.AlterModelOptions(
            name='classicregion',
            options={'verbose_name': 'Classic Region', 'verbose_name_plural': 'Classic Regions'},
        ),
        migrations.AlterUniqueTogether(
            name='classiclevelrecord',
            unique_together=set(),
        ),
    ]
