from platformerdemonlist.admin.platformerleveladmin import CustomSortableAdminMixin, PlatformerLevelAdmin
from platformerdemonlist.admin.platformerplayeradmin import PlatformerPlayerAdmin
from platformerdemonlist.admin.platformerlevelrecordadmin import PlatformerLevelRecordAdmin
from platformerdemonlist.admin.platformerregionadmin import PlatformerRegionAdmin
from platformerdemonlist.admin.platformerlistchangeadmin import PlatformerListChangeAdmin